version: "3.9"
services:
  docker-with-gui-template:
    build: .
    container_name: docker-with-gui-template-container
    network_mode: host
    privileged: true
    volumes:
      - .:/root/DiffOptCBF
      - ..:/home/docker-with-gui-template
    stdin_open: true
    tty: true