version: "3.9"
services:
  docker-with-gui-template:
    build: .
    container_name: docker-with-gui-template-container
    network_mode: host
    # privileged: true
    command: bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    runtime: nvidia
    stdin_open: true
    tty: true